SELECT AO.ANIMAL_ID,
       AO.ANIMAL_TYPE,
       AO.NAME
from ANIMAL_OUTS AO join ANIMAL_INS AI on AO.ANIMAL_ID = AI.ANIMAL_ID
where not AI.SEX_UPON_INTAKE = AO.SEX_UPON_OUTCOME
order by AO.ANIMAL_ID