SELECT FO.PRODUCT_ID,
       FP.PRODUCT_NAME,
       SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER FO INNER JOIN FOOD_PRODUCT FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE '%2022-05%'
GROUP BY 1
ORDER BY 3 DESC, 1