SELECT GU.USER_ID,
       GU.NICKNAME,
       SUM(GB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD GB INNER JOIN USED_GOODS_USER GU ON GB.WRITER_ID = GU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY GB.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY 3