SELECT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCRH.START_DATE like '2022-10%' and CRCC.CAR_TYPE = '세단'
GROUP BY 1
ORDER BY 1 DESC